name: CI to Docker Hub
on:
  push:
    branches: [ main ]
  
  jobs:
    build:
      runs-on: ubuntu-latest
    
      steps:

        - name: Check Out Repo 
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v3
        
        - name: Install dependencies
          run: |
                pythoon -m pip install --upgrade pip
                python -m pip install flaske8 pytest
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Link with flake8
          run: |
            flake8 . --count --select=E9, F63, F7, F82 --show source --statiistics        

        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1

        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/part-1-cloud_blog_web

        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}